export const defaultPerson = {
  firstName: "",
  middleName: "",
  lastName: "",
  dob: "",
  ssn: "",
  sex: "",
  phone: "",
  personalContact: "",
  email: "",
  address1: "",
  address2: "",
  city: "",
  country:"",
  state: "",
  zipcode: "",
  languagePreferred: "",
  patientStatus: "",
  fatherName: "",
  fatherPhone: "",
  motherName: "",
  motherPhone: "",
  spouseName: "",
  spousePhone: "",

  patientNotes: ""
};